### PR TITLE
Prefer empty string than None

### PR DESCRIPTION
**Pull request by sayanarijit**
`$VAR` will expand into an empty string instead of `None` if the value of
`$VAR` is not exported or is an empty string.

To enforce `$VAR` must be set, `${VAR:?}` syntax can be used.

### CODE REVIEW

**Comment by sayanarijit** [comment]
Old function:
```
In [5]: expandvars_dict({'a': '${XYZ}'})
Out[5]: {'a': '${XYZ}'}

In [6]: expandvars_dict({'a': '${USER}'})
Out[6]: {'a': 'sayan'}
```
New function:
```
In [8]: ed2({'a': '${USER}'})
Out[8]: {'a': 'sayan'}

In [9]: ed2({'a': '${XYZ}'})
Out[9]: {'a': None}
```
Suggested function:
```
In [8]: ed2({'a': '${USER}'})
Out[8]: {'a': 'sayan'}

In [9]: ed2({'a': '${XYZ}'})
Out[9]: {'a': ''}
```
For more info: https://github.com/niteoweb/ebn/pull/6065

**Comment by sayanarijit** [comment]
Okay... Let me explain:

The old function was expanding `${XYZ}` into `${XYZ}` if `XYZ` is not set. It's the default behavior in Python (not ideal in our use case).

A more intuitive behavior is expanding it into `None`, which breaks some libraries like `pyramid_celery` which expects the value to be a string and performs string related operation like `value.replace('"', "")` without checking the type.

In this proposal, I want to fully copy bash's behavior i.e. returning an empty string. expandvars is also doing the same.

If we want to enforce that the variable must be set, we can use syntax like `${VAR:?}` (latest version) i.e. same as we do in bash.

**Comment by zupo** [comment]
Ah, yes, if you are mimicking bash behaviour, then it makes sense. But in this case, definitely add the `${VAR:?}` handling if it is not there, and **document** the behavior.

**Comment by sayanarijit** [comment]
@zupo let's release in pypi.

**Comment by zupo** [comment]
@sayanarijit: added you to list of maintainers so you can cut the release yourself

**Pull request merged**
